name = "sso-auth"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "sso-auth-db"
database_id = "2a1052bb-e19f-4de6-9b62-5d22146e0c31"

[vars]
DB_DRIVER = "d1"
NEXT_PUBLIC_APP_NAME = "SSO Auth"
EMAIL_MODE = "console"
